Repository KiranAminPanjwani/Randomized-Color-Lab, pull requests merged in 2022-10, with the labels that each got.

#16 Update documentation file
  README.md
Labels: bug, documentation, good first issue, Hacktoberfest

#28 Added useEffect() to Learn.md
  Learn.md
Labels: Hacktoberfest, hacktoberfest-accepted

#29 feat: add pointer cursor to buttons
  src/pages/Home.css
Labels: Hacktoberfest, hacktoberfest-accepted

#31 Added "copy color" button styling and transition
  package-lock.json
  src/pages/Home.css
  src/pages/Home.jsx
Labels: Hacktoberfest, hacktoberfest-accepted

#30 Fix #22: Copy color buttons shouldn't be able to hightlight
  src/pages/Home.css
Labels: Hacktoberfest, hacktoberfest-accepted

#41 Added hover effect to squares
  src/pages/Home.css
Labels: Hacktoberfest, hacktoberfest-accepted

#55 Update README.md
  README.md
Labels: Hacktoberfest
